name: mobile_project2
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1 # App Icon
  flutter_native_splash: ^2.4.1   # Native Splash
  cupertino_icons: ^1.0.8
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  google_maps_flutter: ^2.18.1
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  google_fonts: ^8.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

    # --- ตั้งค่า App Icon ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon1.png"

# --- ตั้งค่า Splash Screen ---
flutter_native_splash:
  color: "#FFFFFF" # สีพื้นหลัง
  image: "assets/images/icon1.png" 
  android_12:
    image: "assets/images/icon1.png" 