// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr1QPciv6kR-aAjZTQHLpsSbyrzCl4g2U',
    appId: '1:263298222333:web:c6170813550c9c76715694',
    messagingSenderId: '263298222333',
    projectId: 'project2-b2707',
    authDomain: 'project2-b2707.firebaseapp.com',
    storageBucket: 'project2-b2707.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNm-CYsJvPJE-z2QIuXiCNXUxJKjvwI4s',
    appId: '1:263298222333:android:8572817778724145715694',
    messagingSenderId: '263298222333',
    projectId: 'project2-b2707',
    storageBucket: 'project2-b2707.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr1QPciv6kR-aAjZTQHLpsSbyrzCl4g2U',
    appId: '1:263298222333:web:bf20d898cd5b70d0715694',
    messagingSenderId: '263298222333',
    projectId: 'project2-b2707',
    authDomain: 'project2-b2707.firebaseapp.com',
    storageBucket: 'project2-b2707.firebasestorage.app',
  );
}
